travis: qemu_v8: fetch dtc submodule to avoid issues with libfdt-dev
If the libfdt-packe is missing or is too old, QEMU reports the
following error:

ERROR: DTC (libfdt) version >= 1.4.2 not present. Your options:
         (1) Preferred: Install the DTC (libfdt) devel package
         (2) Fetch the DTC submodule, using:
             git submodule update --init dtc

It looks like the version of libfdt-dev that is currently deployed on
travis-ci.org is too old. So, let's do (2).

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>
Reviewed-by: Joakim Bech <joakim.bech@linaro.org>
Reviewed-by: Igor Opaniuk <igor.opaniuk@linaro.org>